PROBLEM_ARCHETYPES = {

    "repetitive_work": {
        "intent": "workflow",
        "sites": [
            "softwarerecs",
            "superuser",
            "webapps",
            "unix",
            "askubuntu",
            "serverfault",
            "softwareengineering",
            "datascience",
            "devops",
        ],
        "queries": [
            "manual process",
            "manual workflow",
            "repetitive task",
            "daily workflow",
            "repeat every day",
            "save time",
            "workflow optimization",
            "automate task",
            "duplicate work",
            "time consuming",
            "too many clicks",
            "copy paste",
            "tedious task",
            "batch processing",
            "bulk operation",
        ],
    },

    "finding_information": {
        "intent": "knowledge_management",
        "sites": [
            "softwarerecs",
            "superuser",
            "webapps",
            "academia",
            "softwareengineering",
            "datascience",
            "genai",
        ],
        "queries": [
            "can't find",
            "find document",
            "search documents",
            "search files",
            "search notes",
            "knowledge base",
            "knowledge management",
            "information retrieval",
            "search across files",
            "find information",
            "search everything",
            "document search",
        ],
    },

    "organization": {
        "intent": "organization",
        "sites": [
            "softwarerecs",
            "superuser",
            "webapps",
            "softwareengineering",
            "academia",
        ],
        "queries": [
            "organize files",
            "organize notes",
            "folder organization",
            "document organization",
            "duplicate files",
            "bookmark management",
            "note organization",
            "folder structure",
            "manage documents",
        ],
    },

    "ai_workflows": {
        "intent": "ai",
        "sites": [
            "softwarerecs",
            "genai",
            "ai",
            "softwareengineering",
            "webapps",
            "datascience",
        ],
        "queries": [
            "chatgpt workflow",
            "claude workflow",
            "prompt management",
            "prompt library",
            "organize prompts",
            "chat history",
            "context management",
            "compare llm",
            "multi ai workflow",
            "agent workflow",
            "llm automation",
            "ai assistant",
        ],
    },

    "research": {
        "intent": "research",
        "sites": [
            "softwarerecs",
            "academia",
            "datascience",
            "stats",
            "bioinformatics",
            "tex",
            "genai",
            "ai",
        ],
        "queries": [
            "literature review",
            "paper organization",
            "citation management",
            "research workflow",
            "annotate pdf",
            "reference management",
            "systematic review",
            "research notes",
            "paper search",
            "reading workflow",
        ],
    },

    "communication": {
        "intent": "communication",
        "sites": [
            "softwarerecs",
            "webapps",
            "superuser",
            "softwareengineering",
            "pm",
        ],
        "queries": [
            "email organization",
            "email overload",
            "calendar management",
            "meeting scheduling",
            "follow up",
            "communication workflow",
            "shared inbox",
            "email workflow",
        ],
    },

    "automation": {
        "intent": "automation",
        "sites": [
            "softwarerecs",
            "superuser",
            "unix",
            "askubuntu",
            "serverfault",
            "devops",
            "softwareengineering",
            "datascience",
            "dba",
        ],
        "queries": [
            "workflow automation",
            "automation",
            "automate task",
            "business automation",
            "manual workflow",
            "no code automation",
            "script repetitive task",
            "cron job",
            "batch automation",
            "scheduled task",
        ],
    },

    "collaboration": {
        "intent": "collaboration",
        "sites": [
            "softwarerecs",
            "webapps",
            "softwareengineering",
            "pm",
            "academia",
        ],
        "queries": [
            "team collaboration",
            "knowledge sharing",
            "shared documents",
            "meeting notes",
            "project tracking",
            "shared workspace",
            "team workflow",
            "documentation sharing",
        ],
    },

    "decision_making": {
        "intent": "decision_support",
        "sites": [
            "softwarerecs",
            "softwareengineering",
            "webapps",
            "genai",
            "ai",
            "datascience",
        ],
        "queries": [
            "compare tools",
            "best tool",
            "choose software",
            "tool recommendation",
            "alternatives",
            "which software",
            "which tool",
            "pros and cons",
            "vs",
        ],
    },

    "pain_language": {
        "intent": "problem_discovery",
        "sites": [
            "softwarerecs",
            "superuser",
            "webapps",
            "unix",
            "askubuntu",
            "softwareengineering",
            "serverfault",
            "devops",
            "datascience",
            "academia",
            "genai",
            "ai",
        ],
        "queries": [
            "struggling with",
            "hard to",
            "difficult to",
            "takes too long",
            "frustrating",
            "workaround",
            "annoying",
            "inefficient",
            "tedious",
            "pain point",
            "too much manual work",
            "there must be a better way",
        ],
    },

}